# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "24fd8948ab3a980274fc750d69c25e79"
name = "delivery-app"
handle = "delivery-app-50"
application_url = "https://tomato-shock-punishment-mental.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "awo-checkout.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_metaobjects,read_shipping,write_delivery_customizations,write_products"

[auth]
redirect_urls = [
  "https://tomato-shock-punishment-mental.trycloudflare.com/auth/callback",
  "https://tomato-shock-punishment-mental.trycloudflare.com/auth/shopify/callback",
  "https://tomato-shock-punishment-mental.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
