api_version = "2024-04"


[[extensions]]
name = "Rename Delivery Option"
handle = "rename-delivery"
type = "function"

  [extensions.capabilities]
  api_access = true
  block_progress = true
  network_access = true

  [[extensions.targeting]]
  target = "purchase.delivery-customization.run"
  input_query = "src/run.graphql"
  export = "rename-delivery"

  [extensions.build]
  command = ""
  path = "dist/rename-function.wasm"


[[extensions]]
name = "Run Delivery Option"
handle = "run"
type = "function"

  [extensions.capabilities]
  api_access = true
  block_progress = true
  network_access = true

  [[extensions.targeting]]
  target = "purchase.delivery-customization.run"
  input_query = "src/run.graphql"
  export = "run"

  [extensions.build]
  command = ""
  path = "dist/run-function.wasm"

[[extensions]]
name = "Hide Delivery Option"
handle = "hide-delivery"
type = "function"

  [extensions.capabilities]
  api_access = true
  block_progress = true
  network_access = true

  [[extensions.targeting]]
  target = "purchase.delivery-customization.run"
  input_query = "src/run.graphql"
  export = "hide-run"

  [extensions.build]
  command = ""
  path = "dist/hide-function.wasm"



description = "t:description"